---
title: "Publications"
output: html_document
---

<br>

### Recent papers

<!-- <div align = "justify"> -->

- **Guzzo, Natália Brambatti**, Heather Goad and Megan Deegan. to appear. Phonological systems in conflict: The acquisition of stress in bilingual French-English. *Proceedings of the 55th Annual Meeting of the Chicago Linguistic Society (CLS 55)*. 

- Xia, Vera Yunxiao, Lydia White and **Natália Brambatti Guzzo**. accepted. Intervention in relative clauses: Effects of relativized minimality on L2 representation and processing. *Second Language Research*.

- Goad, Heather, **Natália Brambatti Guzzo** and Lydia White. accepted. Parsing ambiguous relative clauses in L2 English: Learner sensitivity to prosodic cues. *Studies in Second Language Acquisition*. [[paper](https://ling.auf.net/lingbuzz/005244)]

- **Guzzo, Natália Brambatti** and Guilherme D. Garcia. accepted. Phonological variation and prosodic representation: Clitics in Portuguese-Veneto contact. *Journal of Language Contact*. [[paper](https://ling.auf.net/lingbuzz/004726)]

- **Guzzo, Natália Brambatti**. 2019. Native and non-native patterns in conflict: Lexicon vs. grammar in loanword adaptation in Brazilian Portuguese. *Supplemental Proceedings of the Annual Meeting on Phonology (AMP) 2018*. [[paper](https://journals.linguisticsociety.org/proceedings/index.php/amphonology/article/view/4488)]

- **Guzzo, Natália Brambatti**. 2018. The prosodic representation of composite structures in Brazilian Portuguese. *Journal of Linguistics* 54(4): 683–720. [[paper](http://dx.doi.org/10.1017/S0022226718000099)]

- **Guzzo, Natália Brambatti**, Heather Goad and Guilherme D. Garcia. 2018. What motivates high vowel deletion in Québec French: Foot structure or tonal profile? *Proceedings of the 92nd Annual Meeting of the Linguistic Society of America*. [[paper](https://doi.org/10.3765/plsa.v3i1.4306)]

- Vogel, Irene, Angeliki Athanasopoulou and **Natália Brambatti Guzzo**. 2018. Timing properties of (Brazilian) Portuguese and (European) Spanish. In Lori Repetti and Francisco Ordóñez (Eds.) *Romance Languages and Linguistic Theory 14. Selected papers from the 46th Linguistic Symposium on Romance Languages (LSRL)*, pp. 325–340. Amsterdam: John Benjamins. [[link](https://benjamins.com/catalog/rllt.14)]

- **Guzzo, Natália Brambatti**. 2017. Recursion in Brazilian Portuguese complex compounds. In Ruth Lopes, Juanito Ornelas de Avelar and Sonia Cyrino (Eds.) *Romance Languages and Linguistic Theory 12. Selected papers from the 45th Linguistic Symposium on Romance Languages (LSRL)*, pp. 97–110. Amsterdam: John Benjamins. [[link](https://benjamins.com/catalog/rllt.12)]

- Slabakova, Roumyana, Lydia White and **Natália Brambatti Guzzo**. 2017. Pronoun interpretation in the second language: Effects of computational complexity. *Frontiers in Psychology* 8: 1–12. [[paper](https://doi.org/10.3389/fpsyg.2017.01236)]

- **Guzzo, Natália Brambatti** and Heather Goad. 2017. Overriding default interpretations through prosody: Depictive predicates in Brazilian Portuguese. *Proceedings of the 91st Annual Meeting of the Linguistic Society of America*. [[paper](http://dx.doi.org/10.3765/plsa.v2i0.4077)]

- Garcia, Guilherme D., Heather Goad and **Natália Brambatti Guzzo**. 2017. Footing is not always about stress: Formalizing variable high vowel deletion in Québec French. *Proceedings of 2016 Annual Meeting on Phonology (AMP)*. [[paper](http://dx.doi.org/10.3765/amp.v4i0.3991)]

- Garcia, Guilherme D., Heather Goad and **Natália Brambatti Guzzo**. 2017. L2 acquisition of high vowel deletion in Québec French. *Proceedings of the 41st Boston University Conference on Language Development (BUCLD)*. [[paper](http://www.lingref.com/bucld/41/BUCLD41-22.pdf)]

- White, Lydia, Heather Goad, Jiajia Su, Liz Smeets, Marzieh Mortazavinia, Guilherme D. Garcia and **Natália Brambatti Guzzo**. 2017. Prosodic effects on pronoun interpretation in Italian. *Proceedings of the 41st Boston University Conference on Language Development (BUCLD)*. [[paper](http://www.lingref.com/bucld/41/BUCLD41-60.pdf)]

- Garcia, Guilherme D. and **Natália Brambatti Guzzo**. 2017. The acquisition of English stress by Québec francophones. In Mehmet Yavas, Margaret Kehoe and Walcir Cardoso (Eds.) *Romance-Germanic Bilingual Phonology*, pp. 200–221. Sheffield: Equinox. [[link](https://www.equinoxpub.com/home/romance-germanic-bilingual-phonology-mehmet-yavas-margaret-kehoe-walcir-cardoso/)]

<!-- </div> -->

---

### Recent and upcoming conference presentations

<!-- <div align = "justify"> -->

- Goad, Heather, Lydia White, Guilherme D. Garcia, **Natália Brambatti Guzzo**, Marzieh Mortazavinia, Liz Smeets and Jiajia Su. 2018. Effects of prosody on L2 interpretation of Italian pronouns. Second Language Research Forum (SLRF), Université du Québec à Montréal, Montreal, Canada, Oct 26-28. [talk]

- **Guzzo, Natália Brambatti**. 2018. Native and non-native patterns in conflict: Lexicon vs. grammar in loanword adaptation in Brazilian Portuguese. 2018 Annual Meeting on Phonology (AMP 2018), University of California San Diego, San Diego (CA), USA, Oct 5-7. [[poster](materials/AMP2018_Guzzo.pdf)]

- Goad, Heather, Lydia White, Guilherme D. Garcia, **Natália Brambatti Guzzo**, Marzieh Mortazavinia, Liz Smeets and Jiajia Su. 2018. Pronoun interpretation in L2 Italian: Prosodic effects revisited. 8th Generative Approaches to Language Acquisition North America (GALANA), Indiana University, Bloomington (IN), USA, Sep 27-30. [talk]

- **Guzzo, Natália Brambatti**. 2018. Diminutive structures in a variety of Brazilian Portuguese: A case of prosodic transfer. Symposium on Second Language Acquisition in Honour of Lydia White, McGill University, Montreal, Canada, Aug 31-Sep 1. [talk]

- Goad, Heather, Lydia White, **Natália Brambatti Guzzo**, Guilherme D. Garcia, Marzieh Mortazavinia, Liz Smeets and Jiajia Su. (2018). How prosody affects L2 processing: Pronoun interpretation in L2 Italian. 2nd International Symposium on Bilingual and L2 Processing in Adults and Children (ISBPAC), Technische Universität Braunschweig, Braunschweig, Germany, May 24-25. [poster]

- Athanasopoulou, Angeliki, Irene Vogel and **Natália Brambatti Guzzo**. (2018). Variability and the alignment of pitch accents in Brazilian Portuguese. 48th Linguistic Symposium on Romance Languages (LSRL), York University, Toronto, Canada, Apr 26-28. [talk]

- **Guzzo, Natália Brambatti**, Heather Goad and Guilherme D. Garcia. (2018). What motivates High Vowel Deletion in Québec French: Foot structure or tonal profile? 92nd Annual Meeting of the Linguistic Society of America (LSA), Salt Lake City (UT), USA, Jan 4-8. [talk, [slides](materials/LSA_GuzzoGoadGarcia.pdf)]

- **Guzzo, Natália Brambatti**. (2018). Language contact determines prosodic representation and variation. 92nd Annual Meeting of the Linguistic Society of America (LSA), Salt Lake City (UT), USA, Jan 4-8. [[poster](materials/lsa2018.pdf)]

- Goad, Heather, Lydia White, Guilherme D. Garcia, **Natália Brambatti Guzzo**, Marzieh Mortazavinia, Liz Smeets and Jiajia Su. (2017). Pronoun interpretation in Italian: assessing the effects of prosody. 5th Experimental Psycholinguistics Conference, Maó (Menorca), Spain, Jun 28-30. [talk]

- Goad, Heather, Lydia White, Guilherme D. Garcia, **Natália Brambatti Guzzo**, Marzieh Mortazavinia, Liz Smeets and Jiajia Su. (2017). Effects of pause and stress on pronoun interpretation in L2 Italian. 11th International Symposium on Bilingualism, University of Limerick, Limerick, Ireland, Jun 11-15. [talk]

- **Guzzo, Natália Brambatti**, Heather Goad and Guilherme D. Garcia. (2017). Accessing prosodic structure through indirect evidence: The L2 acquisition of high vowel deletion in Québec French. Annual Meeting of the Canadian Linguistic Association (CLA), Ryerson University, Toronto, Canada, May 27-29. [talk]

- **Guzzo, Natália Brambatti**, Heather Goad and Guilherme D. Garcia. (2017). Learners can acquire structurally-conditioned variation: High vowel deletion in Québec French. 14th Generative Approaches to Second Language Acquisition conference (GASLA 14), University of Southampton, Southampton, UK, Apr 6-9. [talk]

- Goad, Heather, Lydia White, Guilherme D. Garcia, **Natália Brambatti Guzzo**, Marzieh Mortazavinia, Liz Smeets and Jiajia Su. (2017). Pronoun interpretation in L2 Italian: effects of pause and stress. 14th Generative Approaches to Second Language Acquisition conference (GASLA 14), University of Southampton, Southampton, UK, Apr 6-9. [talk]

- **Guzzo, Natália Brambatti** and Heather Goad. (2017). Using acoustic cues to interpret ambiguous sentences: Depictive predicates in Brazilian Portuguese. The Ohio State University Congress on Hispanic and Lusophone Linguistics 2017 (OSUCHiLL), The Ohio State University, Columbus (OH), USA, Mar 31-Apr 1 2017. [talk]

- **Guzzo, Natália Brambatti** and Guilherme D. Garcia. (2017). Probing prosodic representations through vowel reduction in Brazilian Portuguese. The Ohio State University Congress on Hispanic and Lusophone Linguistics 2017 (OSUCHiLL), The Ohio State University, Columbus (OH), USA, Mar 31-Apr 1 2017. [talk]

- **Guzzo, Natália Brambatti** and Heather Goad. (2017). Overriding default interpretations through prosody: Depictive predicates in Brazilian Portuguese. 91st Annual Meeting of the Linguistic Society of America (LSA), Austin (TX), USA, Jan 5-8. [talk, [slides](materials/Guzzo_GoadLSA2017.pps)]
 
<br>

*(See older papers and presentations in my CV.)*

<!-- </div> -->
